### ISSUE TITLE
Feature: Add Support for dynamic fixtures with ERB

### ISSUE THREAD

**Issue by wteuber** [drwl/annotaterb#149] opened 2024-09-05 18:02 UTC
[Dynamic fixtures with ERB](https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html) are available in Rails. They allow including ERB in fixture YAML files.

`annotaterb models` runs into a `Psych::SyntaxError` for [Dynamic fixtures with ERB].

Request: Allow `AnnotateRb::ModelAnnotator::FileParser::YmlParser#parse_yml` to parse dynamic fixtures with ERB.

## Commands

```
$ annotaterb models
```

## Version

- annotaterb version: 4.11.0
- rails version: 7.2.1
- ruby version: 3.3.1

**Comment by drwl** [comment] 2024-09-16 18:51
@wteuber thanks for opening an issue and apologies for the delay --

I'm not too familiar with Dynamic fixtures. Any chance you could create a dummy Rails app and link me to the repo so I can play around with it more?

**Comment by wteuber** [comment] 2024-09-20 19:18
@drwl sure, here is a dummy Rails app: https://github.com/wteuber/annotaterb_issues_149/

Running `annotaterb models` there will result in
```
mapping values are not allowed in this context at line 4 column 14 (Psych::SyntaxError)
```

The users fixture contains ERB (hence "dynamic fixture"): [test/fixtures/users.yml](https://github.com/wteuber/annotaterb_issues_149/blob/main/test/fixtures/users.yml) and can't be parsed properly.

**Comment by drwl** [comment] 2024-10-08 06:27
@wteuber sorry for the very long delay (again), I recently started a new job and have been spending most of my time trying to ramp up quickly. I think now I'm at a good spot where I have time to work on this gem.

Investigating it now -- thanks for providing a reproducible example

**Comment by drwl** [comment] 2024-10-08 06:49
I was able to add a small change that will try loading ERB in a yaml, and it would produce this output:

```yml
# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

<% 1.upto(100) do |i| %>
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
user_<%= i %>:
  name: User <%= i %>
  email: user_<%= i %>@example.com
<% end %>

```

Thoughts on this?

**Comment by wteuber** [comment] 2024-10-14 23:11
Nice work, thanks a lot for looking into this and fixing the issue 👍 
___
Suggestion: I'm not sure if it's worth the effort, but I think adding the schema information above the first line of ERB would improve readability:

```erb
# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
<% 1.upto(100) do |i| %>
user_<%= i %>:
  name: User <%= i %>
  email: user_<%= i %>@example.com
<% end %>
```

What do you think?

**Comment by drwl** [comment] 2024-10-16 06:42
That definitely looks preferable over the current implementation. I'll spend some time more looking into this and timebox it. If I don't end up finding a simple solution for that I'll probably end up merging as is.

**Comment by drwl** [comment] 2024-10-21 01:24
Gonna merge in as is -- it looks like it's gonna take a decent amount of tweaking the parser to support this case. If it ends up being a big bother, I would be more than happy to help with any PR to make it right.

**Comment by drwl** [comment] 2024-11-07 18:21
Gonna close this ticket out since the pr has been merged in and was released a few weeks ago. Feel free to reopen if there are any issues.

**Closed by drwl** 2024-11-07 18:21 UTC
